web:
  build: .
  environment:
    MYENV: EXAMPLE
  volumes:
    - .:/code
scheduled_tasks:
  extends:
    service: web
  command: python tasks_to_run.py
web_run:
  extends:
    service: web
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"