# Generated by Django 3.1.6 on 2021-10-22 07:49

import ViewStocks.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discordTag', models.CharField(max_length=37)),
                ('avatar', models.CharField(max_length=100)),
                ('publicFlags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfaEnabled', models.BooleanField()),
                ('last_login', models.DateTimeField()),
            ],
            managers=[
                ('objects', ViewStocks.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
